apiVersion: v1
kind: Pod
metadata:
  name: todo-list-pod
  namespace: kubernetes-cluster
  labels:
    app: todo-list
spec:
  containers:
  - name: todo-dev
    image: ahmed63/todo-list:v1
    ports:
    - containerPort: 80